### ISSUE TITLE
missing normalize_expression.py file in qtl/src/ folder

### ISSUE THREAD

**Issue by oldregan** [broadinstitute/gtex-pipeline#1]
Where is the normalize_expression.py file? There is just eqtl_prepare_expression.py file in the src/ folder. Are they the same file?

**Comment by francois-a** [comment]
Yes, this file was renamed (please see https://github.com/broadinstitute/gtex-pipeline/commit/63b13b8ced25cf8ab8e7a26f40a495e523630a9b).
