### ISSUE TITLE
Permission denied run_rnaseqc.py

### ISSUE THREAD

**Issue by methionine-Z** [broadinstitute/gtex-pipeline#10]
Hello, I received below error testing run_rnaseqc.py in V8. Other components work out fine.  

 "/bin/bash: /src/run_rnaseqc.py: Permission denied"

Maybe this is an isolated issue, any suggestions? Thanks!

**Comment by francois-a** [comment]
This is fixed in 5934835d43b9c7d4539db9b192a98fc6bca50051
