### ISSUE TITLE
collapse_annotation.py Error

### ISSUE THREAD

**Issue by abayega** [broadinstitute/gtex-pipeline#14]
Hi,

thank you for collapse_annotation.py script. I however, get the error below which I could not figure. Could you kindly assist to edit the script.

Traceback (most recent call last):
  File "/home/banthony/software/gtex-pipeline-master/gene_model/collapse_annotation.py", line 249, in <module>
    annotation = Annotation(args.transcript_gtf)
  File "/home/banthony/software/gtex-pipeline-master/gene_model/collapse_annotation.py", line 84, in __init__
    e = Exon(str(len(t.exons)+1), len(t.exons)+1, attributes['exon_id'], start_pos, end_pos)
UnboundLocalError: local variable 't' referenced before assignment

**Comment by francois-a** [comment]
What GTF are trying to run this on? This may be a formatting issue. Can you try running this on one of the GENCODE GTFs? (for example ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_26/gencode.v26.annotation.gtf.gz)

**Comment by abayega** [comment]
Yep, you are right, it is a formatting issue. I will try to get my gtf formatted as the one you genecode. My gtf filed 3 only has exon, does the script expect for each gene to have 'gene', 'transcript' and 'exon' for field 3?

**Comment by francois-a** [comment]
Yes, you'll need to add a gene and transcript for each group of exons.

**Comment by abayega** [comment]
Finally got the formatting right and it worked well. Thank you for the tool.

**Comment by Anto007** [comment]
Hi,

I ran collapse_annotation.py using python 3.6.2 and got the below error. Any help would be appreciated (the source gtf file was downloaded from NCBI)

python3 collapse_annotation.py GCF_003668045.3_CriGri-PICRH-1.0_genomic.gtf GCF_003668045.3_CriGri-PICRH-1.0_genomic_collapsed.gtf

Traceback (most recent call last):
File "collapse_annotation.py", line 279, in 
annotation = Annotation(args.transcript_gtf)
File "collapse_annotation.py", line 67, in init
attributes[kv[0]] = kv[1]
IndexError: list index out of range

**Comment by GerardoZA** [comment]
I see the same error. 
gtf also downloaded form NCBI - RefSeq

**Comment by francois-a** [comment]
Fixed in 3218db7cba2980ffdf3bca2decddfcae0b2835fe.
