### ISSUE TITLE
Does STAR WDL requires alignment index?

### ISSUE THREAD

**Issue by student-t** [broadinstitute/gtex-pipeline#18]
https://github.com/broadinstitute/gtex-pipeline/blob/master/rnaseq/rnaseq_pipeline_fastq.wdl is the WDL file.

    File fastq1
    File? fastq2
    String prefix

    call star_wdl.star {
        input: fastq1=fastq1, fastq2=fastq2, prefix=prefix
    }

As far as I see, STAR doesn't ask for alignment index. May I ask how this WDL script can work out where to align the reads to?

**Comment by francois-a** [comment]
It does -- the WDL you linked only has to specify arguments that are passed from one task to another. The arguments specific to each task are defined in the corresponding WDL: https://github.com/broadinstitute/gtex-pipeline/blob/master/rnaseq/star.wdl

Please also see the WDL documentation: https://github.com/broadinstitute/wdl/blob/master/versions/draft-3/SPEC.md
