### ISSUE TITLE
Import missing in rnaseq_pipeline_fastq.wdl

### ISSUE THREAD

**Issue by student-t** [broadinstitute/gtex-pipeline#19]
I'm getting an error for WDL from Cromwell:

    Failed to import workflow https://api.firecloud.org/ga4gh/v1/tools/broadinstitute_gtex:samtofastq_v1-0_BETA/versions/3/plain-WDL/descriptor.:
    Bad import https://api.firecloud.org/ga4gh/v1/tools/broadinstitute_gtex:samtofastq_v1-0_BETA/versions/3/plain-WDL/descriptor: Import file not found: 
    https://api.firecloud.org/ga4gh/v1/tools/broadinstitute_gtex:samtofastq_v1-0_BETA/versions/3/plain-WDL/descriptor

It doesn't look like the import URL in https://github.com/broadinstitute/gtex-pipeline/blob/master/rnaseq/rnaseq_pipeline_fastq.wdl are valid. For example, https://api.firecloud.org/ga4gh/v1/tools/broadinstitute_gtex:rsem_v1-0_BETA/versions/3/plain-WDL/descriptor gives a 404 error.

May I ask if this is an expected behaviour? How should I run the WDL script with those imports missing?

**Comment by francois-a** [comment]
Not all of these methods are public in FireCloud (please note the version number in the path). For `rnaseq_pipeline_fastq.wdl`, the following version is: https://github.com/broadinstitute/gtex-pipeline/blob/v9/rnaseq/rnaseq_pipeline_fastq.wdl

If you search the FireCloud methods repository for the `broadinstitute_gtex` namespace you'll see a list of available methods. If you want to run an older version, you'll need to upload the corresponding WDL.
