### ISSUE TITLE
chimMainSegmentMultNmax & -outSAMattributes 

### ISSUE THREAD

**Issue by maegsul** [broadinstitute/gtex-pipeline#2]
Hi,

I think STAR 2.4.2a does not support "chimMainSegmentMultNmax" option, however it is found in run_STAR.py. Therefore it crashes when using STAR 2.4.2a. (However, I am not sure if docker version has 2.4.2a or a later version; since I am not using it).

Same goes for -outSAMattributes , where "ch" is not supported by STAR 2.4.2a.

Cheers,
Fahri

**Comment by francois-a** [comment]
The pipeline uses STAR 2.5.3a, which supports these options.

**Comment by maegsul** [comment]
OK, thanks for informing me! I asked this because GTEx V7 was created using STAR v2.4.2a, RSEM v1.2.22 and RNA-SeQC 1.1.9; which is as also stated by "Image contents and pipeline components" part of RNA-seq pipeline. 

Therefore, is it safe to say the current RNA-seq pipeline is curated for GTEx V8 release (that is expected to be released in late 2017?)? And, will all the options indicated for these tools be the same? I am asking this just to be able to reproduce the similar results using my dataset for the respective tissue; so ideally I aim to align & quantify my reads in the same way as GTEx does. 

Thanks,
Fahri
