### ISSUE TITLE
Version of GENCODE

### ISSUE THREAD

**Issue by 52-hertz-whale** [broadinstitute/gtex-pipeline#22]
Hi, I am using docker image V8 for RNA-seq. I noticed that GENCODE v19 was used in your code, but it also says that V8 will be based on GENCODE v26.
So I am wondering which version of GENCODE should I use for the V8 docker image? I hope to get the same result as RNA-Seq data in GTEx Portal.

Thank you!

**Comment by francois-a** [comment]
V8 will be based on GENCODE 26.

**Comment by 52-hertz-whale** [comment]
So, when running the code from your pipeline, should I use GENCODE v26 files to replace the v19 files in your code (in the pipeline)?
