### ISSUE TITLE
Error running docker eqtl_prepare_expression.py 

### ISSUE THREAD

**Issue by AdrielleM** [broadinstitute/gtex-pipeline#28]
Hi, 

I run the eqtl_prepare_expression pipeline and got this error: 
![Captura de tela de 2019-10-15 14-21-54](https://user-images.githubusercontent.com/29712424/66854240-5e03a080-ef57-11e9-8385-fd60449e9734.png)

Does anyone know how to solve this ?

**Comment by Taylor95** [comment]
I got the same erro, have you solved this?

**Comment by maegsul** [comment]
I have the same error too, has anyone solved this issue?

**Comment by francois-a** [comment]
I'm unable to reproduce this error. Would any of you be able to share the input data you're using?

**Comment by maegsul** [comment]
This is the code that I am running:

`eqtl_prepare_expression.py rnaseqc_output_tpm_file.gct.gz rnaseqc_output_genereads.gct.gz gencode.v24.annotation.genes.gtf sample_participation_lookup.tsv vcf_chr_list.tsv outputEqtlprepareexpression --tpm_threshold 0.1 --count_threshold 6 --sample_frac_threshold 0.2 --normalization_method tmm`

Below are snippets of input files:

> #1.2 |   |   |   |  
> -- | -- | -- | -- | --
> 58380 | 259 |   |   |  
> Name | Description | sorted.sample1.out.bam.gene_tpm.gct.gz | sorted.sample2.out.bam.gene_tpm.gct.gz | sorted.sample3.out.bam.gene_tpm.gct.gz
> ENSG00000223972.5 | DDX11L1 | 0.065775 | 0.018748 | 0.013285
> ENSG00000227232.5 | WASH7P | 2.59764 | 1.61103 | 2.55989
> ENSG00000278267.1 | MIR6859-1 | 0 | 0 | 0

rnaseqc_output_genereads.gct.gz:

> #1.2 |   |   |   |  
> -- | -- | -- | -- | --
> 58380 | 259 |   |   |  
> Name | Description | sorted.sample1.out.bam.gene_reads.gct.gz | sorted.sample2.out.bam.gene_reads.gct.gz | sorted.sample3.out.bam.gene_reads.gct.gz
> ENSG00000223972.5 | DDX11L1 | 3 | 1 | 1
> ENSG00000227232.5 | WASH7P | 91 | 66 | 148
> ENSG00000278267.1 | MIR6859-1 | 0 | 0 | 0

sample_participation_lookup.tsv:

> sample_id       participation_id
> sorted.sample1.out.bam sample1
> sorted.sample2.out.bam   sample2
> sorted.sample3.out.bam  sample3


vcf_chr_list.tsv:

> 1
> 2
> 3
> 4
> 5
> 6
> 7
> 8
> 9
> 10
> 11
> 12
> 13
> 14
> 15
> 16
> 17
> 18
> 19
> 20
> 21
> 22

**Comment by francois-a** [comment]
Thanks! The problem here is that the sample IDs don't match across files: it should consistently be `sorted.sample1.out.bam` (or probably just `sample1`) instead of `sorted.sample1.out.bam.gene_tpm.gct.gz` and `sorted.sample1.out.bam. gene_reads.gct.gz`. The code now throws an explicit error.

**Comment by maegsul** [comment]
Thank you very much @francois-a ! Indeed that was the problem. Now it works very well for me.

**Comment by francois-a** [comment]
Great! This likely also resolves #24.
