### ISSUE TITLE
PEER Covariates

### ISSUE THREAD

**Issue by maegsul** [broadinstitute/gtex-pipeline#3]
Hi,

Is the Rscript provided for PEER factor calculation accounting for already known cofounders? (such as gender and batch). If not, wouldn't we adjust the expression matrix multiple times for the same covariates if PEER is already detecting such cofounders? (and because the next step in the pipeline is combining known covariates with PEER factors)

I've modified the script with "p <- add_argument(p, "--covariates", help="")" and "invisible(PEER_setCovariates(model, argv$covariates))" to avoid this for example, but not sure if that's going to work. 

Thanks,
Fahri

**Comment by francois-a** [comment]
No, we didn't include any covariates when estimating the PEER factors. The genotype covariates and gender (which were the only known covariates added to the PEER factors) were not or only very weakly captured by the PEER factors (see Supplementary Fig. 9 from the latest [GTEx paper](https://www.nature.com/articles/nature24277#supplementary-information)).

**Comment by maegsul** [comment]
Thank you Francois.
