### ISSUE TITLE
utility of bamsync in rnaseq

### ISSUE THREAD

**Issue by KangchengHou** [broadinstitute/gtex-pipeline#30]
Hi,

First thanks for maintaining this super useful repository.
In the documentation of RNAseq pipeline, it says
> sync BAMs (optional; copy QC flags and read group IDs)

I wonder what's the utility of copying QC flags and read group IDs. Is including this step helping anything? 

Thanks!

**Comment by francois-a** [comment]
Hi,

This step was implemented specifically for HiSeq 2000/2500 BAMs that include the vendor QC flag, which would otherwise get lost when realigning BAMs with this pipeline.

**Comment by KangchengHou** [comment]
Thanks for the info, but when will this information be useful in the later step of the pipeline? Is it included as a covariate or sth. like that?

**Comment by francois-a** [comment]
No, this flag isn't used by the pipeline. RNA-SeQC filters reads based on other criteria. But for consistency across GTEx versions (since the BAMs occasionally get replaced with new alignments) we wanted to preserve all information when realigning to new references/annotations.

**Comment by KangchengHou** [comment]
thanks very much for clarifying!
