### ISSUE TITLE
Format of ${sample_participant_lookup}

### ISSUE THREAD

**Issue by jrxubio** [broadinstitute/gtex-pipeline#32]
Hello,
According to this instruction:
The file ${sample_participant_lookup} must contain two columns, sample_id and participant_id, mapping IDs in the expression files to IDs in the VCF (these can be the same).

I generated the file containing lines like:
sample_id       participant_id
0226-SM-5GZZ7   GTEX-1117F
0426-SM-5EGHI   GTEX-1117F
0526-SM-5EGHJ   GTEX-1117F
0626-SM-5N9CS   GTEX-1117F
0726-SM-5GIEN   GTEX-1117F
1326-SM-5EGHH   GTEX-1117F

The columns are separated by tab. 
 
When using eqtl_prepare_expression.py, I have this error:
    raise ValueError('Sample IDs in expression files and participant lookup table must match.')
ValueError: Sample IDs in expression files and participant lookup table must match.

I think the sample-participant file I generated is problematic.

Thanks!

**Comment by francois-a** [comment]
Hi,
This file needs to be in the format GTEX-1117F-0226-SM-5GZZ7	GTEX-1117F
for GTEx samples (tab separated).

**Comment by jrxubio** [comment]
Hi 

Just to double check: GTEX-1117F is a participant, and GTEX-1117F-0226-SM-5GZZ7 is a sample from the participant?

With the above specification, the command line below runs through, 
eqtl_prepare_expression.py GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_tpm.gct.gz GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_tpm.gct.gz ../geneModel/gencode.v26.GRCh38.genes.gtf participant_sample_tpm.txt chr_vcf.txt test  --tpm_threshold 0.1 --count_threshold 6 --sample_frac_threshold 0.2 --normalization_method tmm

However, the resultant test.expression.bed is wierd. It has only 12,821 genes (rows). And each column is a participant, rather than samples. 

Do I have to parse the expression gz files to generate files for each tissues/organs, and then use the eqtl_prepare_expression.py pipeline? If so, how to identify the tissue/organ id from the sample ids? e.g. from GTEX-11DXY-0008-SM-5QGR4; GTEX-11DXY-0011-R10b-SM-DO12C

Thanks.

**Comment by francois-a** [comment]
Hi,

This behavior is expected -- the sample IDs get converted to participant IDs for the selected tissue, so that they match up with the participant IDs in the VCF.

This script filters out genes based on expression thresholds (there are two, for counts and TPMs; please see the documentation of the main function), resulting in a smaller number of rows in the BED file.

To generate the files for a specific tissue, you can provide the sample IDs in a file, and pass that file using the `--sample_id_list` option.

**Comment by jrxubio** [comment]
Thanks.
