### ISSUE TITLE
Stranded setting in RSEM and RNASeQC

### ISSUE THREAD

**Issue by KangchengHou** [broadinstitute/gtex-pipeline#33]
According to the instruction at https://github.com/broadinstitute/gtex-pipeline/tree/master/rnaseq, when running RSEM, there will be a strand-specific setting. However, in the usage in the RNASeQC, we don't specify that. Could you explain why? Thanks very much!

**Comment by francois-a** [comment]
These settings are specific to GTEx samples, which were sequenced with an unstranded protocol. Both tools have options for stranded protocols, and the latest wrappers (currently on the v9 branch) include them: https://github.com/broadinstitute/gtex-pipeline/blob/v9/rnaseq/src/run_rnaseqc.py
