### ISSUE TITLE
run_FastQTL_threaded.py

### ISSUE THREAD

**Issue by jrxubio** [broadinstitute/gtex-pipeline#34]
I got the genotype data from dbGap:
phg001219.v1.GTEx_v8_WGS.genotype-calls-vcf.c1/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_866Indiv.vcf.gz
(It contains all genotypes from all tissues and individuals)

I also successfully generated the *.expression.bed.gz of one tissue as
well as covariates and tbi files etc.

Then I run the command ./fastqtl/python/run_FastQTL_threaded.py ./PhenoGenotypeFiles/RootStudyConsentSet_phs000424.GTEx.v8.p2.c1.GRU/GenotypeFiles/phg001219.v1.GTEx_v8_WGS.genotype-calls-vcf.c1/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_866Indiv.vcf.gz ./tissue9_size176.expression.bed.gz tissue9_size176 --covariates ./tissue9_size176.combined_covariates.txt --window 1e6 --chunks 100 --threads 8 --permute 1000 10000

I tried 8 threads or even 1 thread. 

The error message is 

Processing chunk 99
Processing chunk 100
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/ysm-gpfs/apps/software/Python/3.7.0-fosscuda-2018b/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/ysm-gpfs/apps/software/Python/3.7.0-fosscuda-2018b/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/ysm-gpfs/pi/gerstein/jx98/bin/gtex_eqtl/gtex-pipeline-master/fastqtl/python/run_FastQTL_threaded.py", line 54, in perm_worker
    s = subprocess.check_call(cmd, shell=True, executable='/bin/bash', stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/ysm-gpfs/apps/software/Python/3.7.0-fosscuda-2018b/lib/python3.7/subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command './fastqtl/bin/fastQTL --vcf ./PhenoGenotypeFiles/RootStudyConsentSet_phs000424.GTEx.v8.p2.c1.GRU/GenotypeFiles/phg001219.v1.GTEx_v8_WGS.genotype-calls-vcf.c1/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_866Indiv.vcf.gz --bed ./tissue9_size176.expression.bed.gz --window 1e6 --maf-threshold 0.0 --ma-sample-threshold 0 --interaction-maf-threshold 0 --cov ./tissue9_size176.combined_covariates.txt --permute 1000 10000 --chunk 1 100 --out tissue9_size176_chunk001.txt.gz --log tissue9_size176_chunk001.log' returned non-zero exit status 127.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./fastqtl/python/run_FastQTL_threaded.py", line 95, in <module>
    assert res.get()[0]==0
  File "/ysm-gpfs/apps/software/Python/3.7.0-fosscuda-2018b/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
subprocess.CalledProcessError: Command './fastqtl/bin/fastQTL --vcf ./PhenoGenotypeFiles/RootStudyConsentSet_phs000424.GTEx.v8.p2.c1.GRU/GenotypeFiles/phg001219.v1.GTEx_v8_WGS.genotype-calls-vcf.c1/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_866Indiv.vcf.gz --bed ./tissue9_size176.expression.bed.gz --window 1e6 --maf-threshold 0.0 --ma-sample-threshold 0 --interaction-maf-threshold 0 --cov ./tissue9_size176.combined_covariates.txt --permute 1000 10000 --chunk 1 100 --out tissue9_size176_chunk001.txt.gz --log tissue9_size176_chunk001.log' returned non-zero exit status 127.

I tried to import multprocessing module of pythong. It works. Could you help on debugging the command run? Or is the error due to data format?

Thanks.

**Comment by francois-a** [comment]
Hi,

Please check the last line of the error message:
```
Command './fastqtl/bin/fastQTL --vcf ./PhenoGenotypeFiles/RootStudyConsentSet_phs000424.GTEx.v8.p2.c1.GRU/GenotypeFiles/phg001219.v1.GTEx_v8_WGS.genotype-calls-vcf.c1/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_866Indiv.vcf.gz --bed ./tissue9_size176.expression.bed.gz --window 1e6 --maf-threshold 0.0 --ma-sample-threshold 0 --interaction-maf-threshold 0 --cov ./tissue9_size176.combined_covariates.txt --permute 1000 10000 --chunk 1 100 --out tissue9_size176_chunk001.txt.gz --log tissue9_size176_chunk001.log' returned non-zero exit status 127.
```

Try running that specific command,
```
./fastqtl/bin/fastQTL --vcf ./PhenoGenotypeFiles/RootStudyConsentSet_phs000424.GTEx.v8.p2.c1.GRU/GenotypeFiles/phg001219.v1.GTEx_v8_WGS.genotype-calls-vcf.c1/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_866Indiv.vcf.gz --bed ./tissue9_size176.expression.bed.gz --window 1e6 --maf-threshold 0.0 --ma-sample-threshold 0 --interaction-maf-threshold 0 --cov ./tissue9_size176.combined_covariates.txt --permute 1000 10000 --chunk 1 100 --out tissue9_size176_chunk001.txt.gz --log tissue9_size176_chunk001.log
```
to see what is causing the error.

**Comment by jrxubio** [comment]
Hi 
I ran the command and get the following errors:

Scanning phenotype data in [./tissue9_size176.expression.bed.gz]
  * 10142 phenotypes

Reading phenotype data in [./tissue9_size176.expression.bed.gz]
  * region = chr1:629062-11736084
  * 176 samples included
  * 114 phenotypes included

Reading genotype data in [./PhenoGenotypeFiles/RootStudyConsentSet_phs000424.GTEx.v8.p2.c1.GRU/GenotypeFiles/phg001219.v1.GTEx_v8_WGS.genotype-calls-vcf.c1/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_866Indiv.vcf.gz] in VCF format

ERROR: Genotype data does not overlap with phenotype data, check your files!
Could you let me know how to process the vcf file. Currently, it is the original file I downloaded from dbgap. Thanks.

**Comment by francois-a** [comment]
You need to make sure that the IDs in the expression/phenotype files are the same as in the VCF. For GTEx samples this means that the IDs should be the participant IDs, in the format GTEX-XXXXX.

**Comment by jrxubio** [comment]
The expression file I generated has header "#chr    start   end     gene_id GTEX-11DXW      GTEX-11DZ1      GTEX-11GSO      GTEX-11GSP      GTEX-11UD1      GTEX-11WQC ......"

The vcf file I used is GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_866Indiv.vcf.gz. The last header is "#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  GTEX-1117F      GTEX-111CU      GTEX-111FC      GTEX-111VG  ..."

The vcf file has participant IDs of all individuals (all tissues). And my expression file has the participant IDs for one tissue (I generated it from GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_tpm.gct.gz and GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_reads.gct.gz using the gtex-qtl pipeline).  

So should I parse the columns of that particularly tissue out of the vcf file? Or is there a convenient way by feeding the script a id file? 

My goal is to detect eqtls with my parameters for all the possible tissues in GTEx. Do I have to divided the expression file in to many files for different tissues as I am doing now?

Thanks

**Comment by jrxubio** [comment]
Hi, could you give me advice on my questions? The expression file contains sample IDs that are a subset of the IDs in the vcf file. Do I have to parse the total vcf file to contain the exact same samples IDs as the expression file? Parsing the large vcf file is difficult for me due to insufficient disk space. Thanks

**Comment by jrxubio** [comment]
It works now. The problem was that the gene expression file and the vcf file downloaded from GTEx have different samples. As long as the IDs of a gene expression file is a subset of the IDs in the vcf file, it will work. so no need to parse the vcf file. Thanks

**Comment by francois-a** [comment]
Yes, that's correct -- glad it works now.
