### ISSUE TITLE
combine covariates

### ISSUE THREAD

**Issue by jrxubio** [broadinstitute/gtex-pipeline#35]
According to https://github.com/broadinstitute/gtex-pipeline/tree/master/qtl#3-combine-covariates,

This step generates a combined covariates file, containing genotype PCs, PEER factors, and additional explicit covariates (e.g., genotyping platform).

I did not find how to generate genotype PCs in the GitHub document and GTEx portal. Could you provide more information on that? 

Thanks.

**Comment by francois-a** [comment]
This is now available [here](https://github.com/broadinstitute/gtex-pipeline/blob/master/genotype/compute_genotype_pcs.py).
