### ISSUE TITLE
Identifying the list of all significant variant-gene pairs

### ISSUE THREAD

**Issue by eldadshulman** [broadinstitute/gtex-pipeline#36]
Hi,
Thank you very much for sharing all these scripts.
Is the script used for Identifying the list of all significant variant-gene pairs in this folder?
If so, which one is it?

I am referring to the script that does the following (quoted from  GTEX 2017 paper [supplemental method](https://static-content.springer.com/esm/art%3A10.1038%2Fnature24277/MediaObjects/41586_2017_BFnature24277_MOESM1_ESM.pdf)s):
"To identify the list of all significant variant-gene pairs associated with eGenes, a genome-wide empirical P-value threshold, pt was defined as the empirical P-value of the gene closest to the 0.05 FDR threshold. pt was then used to calculate a nominal P-value threshold for each gene based on the beta distribution model (from FastQTL) of the minimum P-value distribution f(pmin) obtained from the permutations for the gene. Specifically, the nominal threshold was calculated as F −1(pt), where F −1 is the inverse cumulative distribution. For each gene, variants with a nominal P-value below the gene-level threshold were considered significant and included in the final list of variant-gene pairs."

Eldad

**Comment by francois-a** [comment]
Hi,

That script is available here: https://github.com/francois-a/fastqtl/blob/master/python/annotate_outputs.py

For the new pipeline based on tensorQTL, please see here: https://github.com/broadinstitute/tensorqtl/blob/master/tensorqtl/post.py#L201

**Comment by eldadshulman** [comment]
Thank you very much!
