### ISSUE TITLE
to repeat GTEx result

### ISSUE THREAD

**Issue by jrxubio** [broadinstitute/gtex-pipeline#37]
./run_FastQTL_threaded.py GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_866Indiv.vcf.gz #BED# #NAME# --covariates #COVARIATE# --window 1e6 --chunks 100 --threads 16 --threshold 1 --fdr 1 --permute 1000 10000

And for all human genes, each gene has only one eqtl entry output. The tissue I used is the Cells_EBV-transformed_lymphocytes. However, according to the GTEx portal, the tissue has 45,8161. significant variant-gene pair. How can I repeat this result? 

Thanks.

**Comment by francois-a** [comment]
Hi,

To replicate the V8 results, you'll need to use the same VCF: `GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.SHAPEIT2_phased.MAF01.vcf.gz`, available on [AnVIL](https://app.terra.bio/#workspaces/anvil-datastorage/AnVIL_GTEx_V8_hg38).

Then, the permutation pass indeed generates a file with summary statistics for each tested gene, including the top eQTL only. You'll need to calculate the associations for all variant-gene pairs, and then filter them for significant pairs. We now use tensorQTL to perform QTL mapping, and these steps are explained [here](https://github.com/broadinstitute/gtex-v8/blob/master/analyses/GTEx_v8_QTL_mapping.ipynb).

**Comment by jrxubio** [comment]
Hi,

Could you provide more information/docs/papers on the reasonings/logic about going from the top eqtl to multiple eqtls. 

I do not need to repeat the GTEx result exactly. Instead, I am just trying to get not only the top eQTL for each gene but more eqtls with q-value, fdr etc. 
Can I achieve this based on the fastqtl tool not tansorQTL? 

Thanks!

**Comment by francois-a** [comment]
The script for generating the list of significant variant-gene pairs for FastQTL is provided here: https://github.com/francois-a/fastqtl/blob/master/python/annotate_outputs.py

**Comment by hnaeem** [comment]
Dear,

I was wondering if there is a workflow for annotate_outputs.py ? How does the annotate_outputs.py work - calculating and filtering at FDR (i.e., 0.05)? What happens If we apply the multiple testing correction on P-values in nominal pass, will the results be same?
