### ISSUE TITLE
Homo_sapiens_assembly19

### ISSUE THREAD

**Issue by gouthamatla** [broadinstitute/gtex-pipeline#39]
I am wondering why the assembly in v8 is named Homo_sapiens_assembly19 in rnaseq folder under building indexes. Shouldnt it be hg38 ? The original documentation on GTEX website says they used v26 of gencode and hg38 genome. Here it looks opposite:

```
docker run --rm -v $path_to_references:/data -t broadinstitute/gtex_rnaseq:V8 \
    /bin/bash -c "STAR \
        --runMode genomeGenerate \
        --genomeDir /data/star_index_oh75 \
        --genomeFastaFiles /data/Homo_sapiens_assembly19.fasta \
        --sjdbGTFfile /data/gencode.v19.annotation.patched_contigs.gtf \
        --sjdbOverhang 75 \
        --runThreadN 4"
```

**Comment by francois-a** [comment]
Thanks for pointing this out. The references have been fixed.
