### ISSUE TITLE
reference_junctions file

### ISSUE THREAD

**Issue by gouthamatla** [broadinstitute/gtex-pipeline#40]
Hi All,

I would like to know where is the reference_junctions file that is required for the script:

`gtex-pipeline/rnaseq/src/process_star_junctions.py`

If not, how can I generate it ?

**Comment by francois-a** [comment]
This file (tsv) should be a list of all junctions in the reference annotation, with `chr, intron_start, intron_end, gene_id` columns. You can generate it as follows (the `qtl` package is on [pypi](https://pypi.org/project/qtl/)):

```
import qtl.annotation as annotation
annot = annotation.Annotation('gencode.v26.GRCh38.annotation.gtf')
junctions_df = annot.get_junctions()
junctions_df.to_csv('gencode.v26.GRCh38.junctions.txt', sep='\t', index=False)
```

**Comment by gouthamatla** [comment]
Thanks for very quick response.
