### ISSUE TITLE
Leafcutter junction files

### ISSUE THREAD

**Issue by gouthamatla** [broadinstitute/gtex-pipeline#41]
Hi All,

I am curious to know if leafcutter raw junction counts are available somewhere. I could see exon-exon junction counts file, but all the splicing analysis is done on leafcutter generated junctions. I also saw that the normalized phenotype  file used for leafcutter is available but I would like to know if I can access the raw junction counts from leafcutter directly or via google cloud. 

Thanks,
Goutham A

**Comment by francois-a** [comment]
Hi,
The raw counts matrices from LeafCutter are now available at [gs://gtex-resources/GTEx_Analysis_v8_QTLs/GTEx_Analysis_v8_sQTL_leafcutter_counts.tar](https://console.cloud.google.com/storage/browser/gtex-resources/GTEx_Analysis_v8_QTLs).

**Comment by gouthamatla** [comment]
Wow. Thank you very much
