### ISSUE TITLE
question about gene number after normalizing in eQTL pipeline

### ISSUE THREAD

**Issue by Taylor95** [broadinstitute/gtex-pipeline#43]
Hi,
I run the eqtl_prepare_expression pipeline and set the same expression thresholds as the example. I'm confused that expression values of  some genes I'm concerned about in GCT files are well above the threshold but removed in BED file. This is why?

**Comment by muzilily** [comment]
Maybe you can check to see if the gene order in the input TPM and READCOUNT files is the same.

**Comment by Taylor95** [comment]
Yes, they are in the same order.
