### ISSUE TITLE
I get an error running run_star.py script

### ISSUE THREAD

**Issue by Rimsk** [broadinstitute/gtex-pipeline#45]
Hi, I am getting an error running the STAR. Can you please help me with this. I downloaded the Index file from here
https://github.com/broadinstitute/gtex-pipeline/blob/master/TOPMed_RNAseq_pipeline.md (STAR index: STAR_genome_GRCh38_noALT_noHLA_noDecoy_ERCC_v30_oh100.tar.gz). 

The resultant file gets empty bam file and log file.

docker run --rm -v $path_to_data:/data -t broadinstitute/gtex_rnaseq:V8     /bin/bash -c "/src/run_STAR.py \
        /data/STAR_genome_GRCh38_noALT_noHLA_noDecoy_ERCC_v30_oh100 \
        /data/${sample_id}_1.fastq.gz \
        /data/${sample_id}_2.fastq.gz \
        ${sample_id} \
        --threads 4 \
        --output_dir /data/star_out"
Jun 24 18:16:56 ..... started STAR run
Jun 24 18:16:57 ..... loading genome
Traceback (most recent call last):
  File "/src/run_STAR.py", line 92, in <module>
    subprocess.check_call(cmd, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'STAR --runMode alignReads --runThreadN 4 --genomeDir /data/STAR_genome_GRCh38_noALT_noHLA_noDecoy_ERCC_v30_oh100 --twopassMode Basic --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverLmax 0.1 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --outFilterType BySJout --outFilterScoreMinOverLread 0.33 --outFilterMatchNminOverLread 0.33 --limitSjdbInsertNsj 1200000 --readFilesIn /data/C42B_1.fastq.gz /data/C42B_2.fastq.gz --readFilesCommand zcat --outFileNamePrefix /data/star_out/C42B. --outSAMstrandField intronMotif --outFilterIntronMotifs None --alignSoftClipAtReferenceEnds Yes --quantMode TranscriptomeSAM GeneCounts --outSAMtype BAM Unsorted --outSAMunmapped Within --genomeLoad NoSharedMemory --chimSegmentMin 15 --chimJunctionOverhangMin 15 --chimOutType WithinBAM SoftClip --chimMainSegmentMultNmax 1 --outSAMattributes NH HI AS nM NM ch --outSAMattrRGline ID:rg1 SM:sm1' returned non-zero exit status -9

Regards
Rimpi

**Comment by francois-a** [comment]
Hi, this is likely because you're using a newer version of STAR than was used to generate the index (2.6.1d). Can you run the STAR command separately to see if you get a more specific error message?

```
STAR --runMode alignReads --runThreadN 4 --genomeDir /data/STAR_genome_GRCh38_noALT_noHLA_noDecoy_ERCC_v30_oh100 --twopassMode Basic --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverLmax 0.1 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --outFilterType BySJout --outFilterScoreMinOverLread 0.33 --outFilterMatchNminOverLread 0.33 --limitSjdbInsertNsj 1200000 --readFilesIn /data/C42B_1.fastq.gz /data/C42B_2.fastq.gz --readFilesCommand zcat --outFileNamePrefix /data/star_out/C42B. --outSAMstrandField intronMotif --outFilterIntronMotifs None --alignSoftClipAtReferenceEnds Yes --quantMode TranscriptomeSAM GeneCounts --outSAMtype BAM Unsorted --outSAMunmapped Within --genomeLoad NoSharedMemory --chimSegmentMin 15 --chimJunctionOverhangMin 15 --chimOutType WithinBAM SoftClip --chimMainSegmentMultNmax 1 --outSAMattributes NH HI AS nM NM ch --outSAMattrRGline ID:rg1 SM:sm1
```

**Comment by Rimsk** [comment]
Hi, 

I downloaded the docker version. 
the log.out file I get states 
STAR version=STAR_2.5.3a
STAR compilation time,server,dir=Thu Aug 2 19:50:26 UTC 2018 e7eddde82bec:/opt/STAR-2.5.3a/source
##### DEFAULT parameters:
versionSTAR                       20201
versionGenome                     20101   20200   
parametersFiles                   -   
sysShell                          -
runMode                           alignReads
runThreadN                        1
runDirPerm                        User_RWX
runRNGseed                        777
genomeDir                         ./GenomeDir/
genomeLoad                        NoSharedMemory

**Comment by francois-a** [comment]
What output do you get when running the STAR command above directly (as opposed to the Python wrapper)?
