### ISSUE TITLE
question for run  eqtl_prepare_expression.py 

### ISSUE THREAD

**Issue by androidpifu** [broadinstitute/gtex-pipeline#47]
when I run eqtl_prepare_expression.py ，it show error message：
Loading expression data
Traceback (most recent call last):
  File "eqtl_prepare_expression.py", line 177, in <module>
    raise ValueError('Sample IDs in expression files and participant lookup table must match.')
ValueError: Sample IDs in expression files and participant lookup table must match.

 Which files do I get the SampeID and  participantID from?  Is SampeID from counts_gct files？is participantID from genotype file？

**Comment by francois-a** [comment]
Yes, the sample IDs are the IDs from the expression file, and the participant IDs from the VCF. If these are the same in your data, the `sample_participant_lookup` file should have two identical columns.
