### ISSUE TITLE
Error during Fastq conversion

### ISSUE THREAD

**Issue by nelsonchanhk** [broadinstitute/gtex-pipeline#49]
I'm trying the rnaseq pipeline with docker. At the fastq conversion step, the following error occurred. Would be grateful if you can advise. Thank you very much!

sudo docker run --rm -v $path_to_data:/data -t broadinstitute/gtex_rnaseq:V8 \
>     /bin/bash -c "/src/run_SamToFastq.py /data/$input_bam -p ${sample_id} -o /data"
[Nov 07 01:04:25] Starting SamToFastq
[Sat Nov 07 01:04:25 UTC 2020] picard.sam.SamToFastq INPUT=/data/HA10YLS.bam FASTQ=read1_pipe SECOND_END_FASTQ=read2_pip                                                            e UNPAIRED_FASTQ=read0_pipe INCLUDE_NON_PF_READS=true INCLUDE_NON_PRIMARY_ALIGNMENTS=false VALIDATION_STRINGENCY=SILENT                                                                OUTPUT_PER_RG=false RG_TAG=PU RE_REVERSE=true INTERLEAVE=false CLIPPING_MIN_LENGTH=0 READ1_TRIM=0 READ2_TRIM=0 VERBOS                                                            ITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT                                                            _SECRETS=client_secrets.json
[Sat Nov 07 01:04:25 UTC 2020] Executing as root@cee0d84bfc96 on Linux 5.3.0-64-generic amd64; OpenJDK 64-Bit Server VM                                                             1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12; Picard version: 2.9.0-1-gf5b9f50-SNAPSHOT
INFO    2020-11-07 01:04:35     SamToFastq      Processed     1,000,000 records.  Elapsed time: 00:00:09s.  Time for las                                                            t 1,000,000:    9s.  Last read position: 1:27,415,567
INFO    2020-11-07 01:04:44     SamToFastq      Processed     2,000,000 records.  Elapsed time: 00:00:18s.  Time for las                                                            t 1,000,000:    9s.  Last read position: 1:43,164,794
INFO    2020-11-07 01:04:53     SamToFastq      Processed     3,000,000 records.  Elapsed time: 00:00:27s.  Time for las                                                            t 1,000,000:    8s.  Last read position: 1:91,716,929
INFO    2020-11-07 01:05:01     SamToFastq      Processed     4,000,000 records.  Elapsed time: 00:00:35s.  Time for las                                                            t 1,000,000:    8s.  Last read position: 1:117,624,489
INFO    2020-11-07 01:05:10     SamToFastq      Processed     5,000,000 records.  Elapsed time: 00:00:44s.  Time for las                                                            t 1,000,000:    8s.  Last read position: 1:153,855,959
INFO    2020-11-07 01:05:18     SamToFastq      Processed     6,000,000 records.  Elapsed time: 00:00:52s.  Time for las                                                            t 1,000,000:    8s.  Last read position: 1:178,824,140
INFO    2020-11-07 01:05:26     SamToFastq      Processed     7,000,000 records.  Elapsed time: 00:01:00s.  Time for las                                                            t 1,000,000:    8s.  Last read position: 1:205,087,027
INFO    2020-11-07 01:05:34     SamToFastq      Processed     8,000,000 records.  Elapsed time: 00:01:08s.  Time for last 1,000,000:    8s.  Last read position: 1:244,318,744
INFO    2020-11-07 01:05:42     SamToFastq      Processed     9,000,000 records.  Elapsed time: 00:01:16s.  Time for last 1,000,000:    7s.  Last read position: 10:22,636,254
INFO    2020-11-07 01:05:50     SamToFastq      Processed    10,000,000 records.  Elapsed time: 00:01:24s.  Time for last 1,000,000:    8s.  Last read position: 10:68,338,518
INFO    2020-11-07 01:05:58     SamToFastq      Processed    11,000,000 records.  Elapsed time: 00:01:32s.  Time for last 1,000,000:    8s.  Last read position: 10:96,535,790
INFO    2020-11-07 01:06:06     SamToFastq      Processed    12,000,000 records.  Elapsed time: 00:01:40s.  Time for last 1,000,000:    8s.  Last read position: 11:1,880,170
INFO    2020-11-07 01:06:10     SamToFastq      Processed    13,000,000 records.  Elapsed time: 00:01:44s.  Time for last 1,000,000:    3s.  Last read position: 11:5,225,474
INFO    2020-11-07 01:06:19     SamToFastq      Processed    14,000,000 records.  Elapsed time: 00:01:53s.  Time for last 1,000,000:    8s.  Last read position: 11:5,225,493
INFO    2020-11-07 01:06:33     SamToFastq      Processed    15,000,000 records.  Elapsed time: 00:02:07s.  Time for last 1,000,000:   14s.  Last read position: 11:5,225,528
INFO    2020-11-07 01:06:39     SamToFastq      Processed    16,000,000 records.  Elapsed time: 00:02:13s.  Time for last 1,000,000:    6s.  Last read position: 11:5,225,556
INFO    2020-11-07 01:07:04     SamToFastq      Processed    17,000,000 records.  Elapsed time: 00:02:38s.  Time for last 1,000,000:   25s.  Last read position: 11:5,225,581
INFO    2020-11-07 01:07:57     SamToFastq      Processed    18,000,000 records.  Elapsed time: 00:03:31s.  Time for last 1,000,000:   52s.  Last read position: 11:5,225,589
INFO    2020-11-07 01:08:51     SamToFastq      Processed    19,000,000 records.  Elapsed time: 00:04:25s.  Time for last 1,000,000:   53s.  Last read position: 11:5,225,601
INFO    2020-11-07 01:10:25     SamToFastq      Processed    20,000,000 records.  Elapsed time: 00:05:59s.  Time for last 1,000,000:   94s.  Last read position: 11:5,225,620
INFO    2020-11-07 01:12:17     SamToFastq      Processed    21,000,000 records.  Elapsed time: 00:07:51s.  Time for last 1,000,000:  112s.  Last read position: 11:5,225,647
INFO    2020-11-07 01:13:46     SamToFastq      Processed    22,000,000 records.  Elapsed time: 00:09:20s.  Time for last 1,000,000:   89s.  Last read position: 11:5,225,657
INFO    2020-11-07 01:15:05     SamToFastq      Processed    23,000,000 records.  Elapsed time: 00:10:39s.  Time for last 1,000,000:   78s.  Last read position: 11:5,225,669
INFO    2020-11-07 01:16:50     SamToFastq      Processed    24,000,000 records.  Elapsed time: 00:12:24s.  Time for last 1,000,000:  104s.  Last read position: 11:5,225,672
INFO    2020-11-07 01:31:59     SamToFastq      Processed    25,000,000 records.  Elapsed time: 00:27:33s.  Time for last 1,000,000:  909s.  Last read position: 11:5,225,692
INFO    2020-11-07 01:35:20     SamToFastq      Processed    26,000,000 records.  Elapsed time: 00:30:54s.  Time for last 1,000,000:  200s.  Last read position: 11:5,225,705
INFO    2020-11-07 01:36:50     SamToFastq      Processed    27,000,000 records.  Elapsed time: 00:32:24s.  Time for last 1,000,000:   90s.  Last read position: 11:5,226,586
INFO    2020-11-07 01:37:15     SamToFastq      Processed    28,000,000 records.  Elapsed time: 00:32:49s.  Time for last 1,000,000:   24s.  Last read position: 11:5,226,603
INFO    2020-11-07 01:37:36     SamToFastq      Processed    29,000,000 records.  Elapsed time: 00:33:10s.  Time for last 1,000,000:   21s.  Last read position: 11:5,226,620
INFO    2020-11-07 01:37:46     SamToFastq      Processed    30,000,000 records.  Elapsed time: 00:33:20s.  Time for last 1,000,000:    9s.  Last read position: 11:5,226,633
INFO    2020-11-07 01:38:08     SamToFastq      Processed    31,000,000 records.  Elapsed time: 00:33:42s.  Time for last 1,000,000:   22s.  Last read position: 11:5,226,647
INFO    2020-11-07 01:39:22     SamToFastq      Processed    32,000,000 records.  Elapsed time: 00:34:56s.  Time for last 1,000,000:   73s.  Last read position: 11:5,226,662
INFO    2020-11-07 01:40:54     SamToFastq      Processed    33,000,000 records.  Elapsed time: 00:36:28s.  Time for last 1,000,000:   92s.  Last read position: 11:5,226,687
INFO    2020-11-07 01:42:27     SamToFastq      Processed    34,000,000 records.  Elapsed time: 00:38:01s.  Time for last 1,000,000:   93s.  Last read position: 11:5,226,721
INFO    2020-11-07 01:43:57     SamToFastq      Processed    35,000,000 records.  Elapsed time: 00:39:31s.  Time for last 1,000,000:   89s.  Last read position: 11:5,226,753
INFO    2020-11-07 01:44:12     SamToFastq      Processed    36,000,000 records.  Elapsed time: 00:39:46s.  Time for last 1,000,000:   15s.  Last read position: 11:5,226,771
INFO    2020-11-07 01:44:28     SamToFastq      Processed    37,000,000 records.  Elapsed time: 00:40:02s.  Time for last 1,000,000:   15s.  Last read position: 11:5,226,774
INFO    2020-11-07 01:44:49     SamToFastq      Processed    38,000,000 records.  Elapsed time: 00:40:23s.  Time for last 1,000,000:   21s.  Last read position: 11:5,226,776
INFO    2020-11-07 01:45:01     SamToFastq      Processed    39,000,000 records.  Elapsed time: 00:40:35s.  Time for last 1,000,000:   11s.  Last read position: 11:10,766,183
INFO    2020-11-07 01:45:09     SamToFastq      Processed    40,000,000 records.  Elapsed time: 00:40:43s.  Time for last 1,000,000:    8s.  Last read position: 11:62,522,604
INFO    2020-11-07 01:45:17     SamToFastq      Processed    41,000,000 records.  Elapsed time: 00:40:51s.  Time for last 1,000,000:    8s.  Last read position: 11:65,502,777
INFO    2020-11-07 01:45:26     SamToFastq      Processed    42,000,000 records.  Elapsed time: 00:41:00s.  Time for last 1,000,000:    8s.  Last read position: 11:76,990,676
INFO    2020-11-07 01:45:34     SamToFastq      Processed    43,000,000 records.  Elapsed time: 00:41:08s.  Time for last 1,000,000:    8s.  Last read position: 11:121,496,986
INFO    2020-11-07 01:45:42     SamToFastq      Processed    44,000,000 records.  Elapsed time: 00:41:16s.  Time for last 1,000,000:    8s.  Last read position: 12:10,704,125
INFO    2020-11-07 01:45:50     SamToFastq      Processed    45,000,000 records.  Elapsed time: 00:41:24s.  Time for last 1,000,000:    8s.  Last read position: 12:50,461,337
INFO    2020-11-07 01:45:58     SamToFastq      Processed    46,000,000 records.  Elapsed time: 00:41:32s.  Time for last 1,000,000:    8s.  Last read position: 12:71,840,291
INFO    2020-11-07 01:46:06     SamToFastq      Processed    47,000,000 records.  Elapsed time: 00:41:40s.  Time for last 1,000,000:    8s.  Last read position: 12:112,314,456
INFO    2020-11-07 01:46:14     SamToFastq      Processed    48,000,000 records.  Elapsed time: 00:41:48s.  Time for last 1,000,000:    8s.  Last read position: 13:28,198,124
INFO    2020-11-07 01:46:22     SamToFastq      Processed    49,000,000 records.  Elapsed time: 00:41:56s.  Time for last 1,000,000:    8s.  Last read position: 13:77,191,780
INFO    2020-11-07 01:46:30     SamToFastq      Processed    50,000,000 records.  Elapsed time: 00:42:04s.  Time for last 1,000,000:    8s.  Last read position: 14:35,400,666
INFO    2020-11-07 01:46:35     SamToFastq      Processed    51,000,000 records.  Elapsed time: 00:42:09s.  Time for last 1,000,000:    4s.  Last read position: 14:49,586,632
INFO    2020-11-07 01:46:49     SamToFastq      Processed    52,000,000 records.  Elapsed time: 00:42:23s.  Time for last 1,000,000:   14s.  Last read position: 14:49,586,718
INFO    2020-11-07 01:46:55     SamToFastq      Processed    53,000,000 records.  Elapsed time: 00:42:29s.  Time for last 1,000,000:    6s.  Last read position: 14:49,862,578
INFO    2020-11-07 01:47:08     SamToFastq      Processed    54,000,000 records.  Elapsed time: 00:42:42s.  Time for last 1,000,000:   13s.  Last read position: 14:49,862,687
INFO    2020-11-07 01:47:18     SamToFastq      Processed    55,000,000 records.  Elapsed time: 00:42:52s.  Time for last 1,000,000:    9s.  Last read position: 14:71,390,545
INFO    2020-11-07 01:47:26     SamToFastq      Processed    56,000,000 records.  Elapsed time: 00:43:00s.  Time for last 1,000,000:    8s.  Last read position: 14:105,644,571
INFO    2020-11-07 01:47:34     SamToFastq      Processed    57,000,000 records.  Elapsed time: 00:43:08s.  Time for last 1,000,000:    8s.  Last read position: 15:56,700,946
INFO    2020-11-07 01:47:42     SamToFastq      Processed    58,000,000 records.  Elapsed time: 00:43:16s.  Time for last 1,000,000:    8s.  Last read position: 15:82,372,502
INFO    2020-11-07 01:47:49     SamToFastq      Processed    59,000,000 records.  Elapsed time: 00:43:23s.  Time for last 1,000,000:    7s.  Last read position: 16:172,890
INFO    2020-11-07 01:48:07     SamToFastq      Processed    60,000,000 records.  Elapsed time: 00:43:41s.  Time for last 1,000,000:   17s.  Last read position: 16:172,896
INFO    2020-11-07 01:48:14     SamToFastq      Processed    61,000,000 records.  Elapsed time: 00:43:48s.  Time for last 1,000,000:    7s.  Last read position: 16:172,901
INFO    2020-11-07 01:48:23     SamToFastq      Processed    62,000,000 records.  Elapsed time: 00:43:57s.  Time for last 1,000,000:    8s.  Last read position: 16:172,908
INFO    2020-11-07 01:50:46     SamToFastq      Processed    63,000,000 records.  Elapsed time: 00:46:20s.  Time for last 1,000,000:  142s.  Last read position: 16:172,939
[Sat Nov 07 02:03:15 UTC 2020] picard.sam.SamToFastq done. Elapsed time: 58.83 minutes.
Runtime.totalMemory()=4898947072
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at htsjdk.samtools.BAMRecordCodec.decode(BAMRecordCodec.java:198)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.getNextRecord(BAMFileReader.java:813)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:787)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:781)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:751)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:569)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:543)
        at picard.sam.SamToFastq.doWork(SamToFastq.java:174)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:104)
Traceback (most recent call last):
  File "/src/run_SamToFastq.py", line 52, in <module>
    +' VALIDATION_STRINGENCY=SILENT FASTQ=read1_pipe SECOND_END_FASTQ=read2_pipe UNPAIRED_FASTQ=read0_pipe', shell=True)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'java -jar -Xmx8g /opt/picard-tools/picard.jar SamToFastq INPUT=/data/HA10YLS.bam INCLUDE_NON_PF_READS=true INCLUDE_NON_PRIMARY_ALIGNMENTS=false VALIDATION_STRINGENCY=SILENT FASTQ=read1_pipe SECOND_END_FASTQ=read2_pipe UNPAIRED_FASTQ=read0_pipe' returned non-zero exit status 1

**Comment by xiyasong** [comment]
Hi!  I have met nearly the same error, but I didn't find the solution for this. Could you tell me how do you fix it? Mine stopped at Processed 3,000,000records.
