### ISSUE TITLE
Error at running RNA-SeQC from docker

### ISSUE THREAD

**Issue by nelsonchanhk** [broadinstitute/gtex-pipeline#50]
Hello, I'm running the RNA-seq pipeline with docker gtex_rnaseq:V8 at the RNA-SeQC, the built in RNA-SeQC is supposed to be v2.3.6 but when I run the docker, the following error appeared. Is the docker is still referring to an older version of RNA-SeQC? Your help is much appreciated. Thank you!

nelson@hemepath:~/OPERATION/GTEX/data$ docker run --rm -v $path_to_data:/data -t broadinstitute/gtex_rnaseq:V8     /bin/                                          bash -c "/src/run_rnaseqc.py \
    ${sample_id}.Aligned.sortedByCoord.out.md.bam \
    ${genes_gtf} \
    ${genome_fasta} \
    ${sample_id} \
    --output_dir /data"
[Nov 12 01:00:24] Running RNA-SeQC
  * command: "java -Xmx4g -jar /opt/RNA-SeQC_1.1.9/RNA-SeQC.jar -n 1000 -s HA10YLS,HA10YLS.Aligned.sortedByCoord.out.md.                                          bam,HA10YLS -t GENCODE_gencode.v26.GRCh38.genes.gtf -r references_Homo_sapiens_assembly38_noALT_noHLA_noDecoy.fasta -o /                                          data -noDoC -strictMode -gatkFlags --allow_potentially_misencoded_quality_scores"
RNA-SeQC v1.1.9 06/26/16
Additional GATK flags provided: --allow_potentially_misencoded_quality_scores
Creating rRNA Interval List based on given GTF annotations
Retriving contig names from reference
         contig names in reference: 195
Loading GTF for Read Counting
Converting to refGene
Transcript objects to RefGen format:    0 s
Running IntronicExpressionReadBlock Walker ....
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.broadinstitute.sting.gatk.GenomeAnalysisEngine.<init>(GenomeAnalysisEngine.java:160)
        at org.broadinstitute.sting.gatk.CommandLineExecutable.<init>(CommandLineExecutable.java:53)
        at org.broadinstitute.sting.gatk.CommandLineGATK.<init>(CommandLineGATK.java:54)
        at org.broadinstitute.cga.rnaseq.gatk.GATKTools.runIntronReadCount(GATKTools.java:203)
        at org.broadinstitute.cga.rnaseq.ReadCountMetrics.runRegionCounting(ReadCountMetrics.java:220)
        at org.broadinstitute.cga.rnaseq.ReadCountMetrics.runReadCountMetrics(ReadCountMetrics.java:59)
        at org.broadinstitute.cga.rnaseq.RNASeqMetrics.runMetrics(RNASeqMetrics.java:211)
        at org.broadinstitute.cga.rnaseq.RNASeqMetrics.execute(RNASeqMetrics.java:162)
        at org.broadinstitute.cga.rnaseq.RNASeqMetrics.main(RNASeqMetrics.java:133)
Caused by: java.lang.NullPointerException
        at org.reflections.Reflections.scan(Reflections.java:220)
        at org.reflections.Reflections.scan(Reflections.java:166)
        at org.reflections.Reflections.<init>(Reflections.java:94)
        at org.broadinstitute.sting.utils.classloader.PluginManager.<clinit>(PluginManager.java:77)
        ... 9 more
Traceback (most recent call last):
  File "/src/run_rnaseqc.py", line 102, in <module>
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'java -Xmx4g -jar /opt/RNA-SeQC_1.1.9/RNA-SeQC.jar -n 1000 -s HA10YLS,HA10YLS.Ali                                          gned.sortedByCoord.out.md.bam,HA10YLS -t GENCODE_gencode.v26.GRCh38.genes.gtf -r references_Homo_sapiens_assembly38_noAL                                          T_noHLA_noDecoy.fasta -o /data -noDoC -strictMode -gatkFlags --allow_potentially_misencoded_quality_scores' returned non                                          -zero exit status 1
nelson@hemepath:~/OPERATION/GTEX/data$ docker run --rm -v $path_to_data:/data -t broadinstitute/gtex_rnaseq:V8 \
>     /bin/bash -c "java -version"
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

**Comment by francois-a** [comment]
Hi, for V8, the RNA-SeQC version used was 1.1.9 (see [here](https://github.com/broadinstitute/gtex-pipeline/tree/master/rnaseq)). To use v2.3.6, please use the docker tag V10 (see [here](https://github.com/broadinstitute/gtex-pipeline/blob/v10/rnaseq/Dockerfile)).

**Comment by nelsonchanhk** [comment]
Thank you @francois-a for your speedy reply. As I was going to compare my sample with GTC files from GTEx Analysis V8 (dbGaP Accession phs000424.v8.p2). Would it be a problem if I use the V10 docker. Or should I use V8 while trying to force it to run JAVA v1.7? Thank you very much in advance.

> Hi, for V8, the RNA-SeQC version used was 1.1.9 (see [here](https://github.com/broadinstitute/gtex-pipeline/tree/master/rnaseq)). To use v2.3.6, please use the docker tag V10 (see [here](https://github.com/broadinstitute/gtex-pipeline/blob/v10/rnaseq/Dockerfile)).

**Comment by francois-a** [comment]
There are some differences (mostly minor, but some of the metrics have changed) in the output from RNA-SeQC 2.3.6 vs 1.1.9, so for these comparisons I recommend using the V8 docker.

**Comment by nelsonchanhk** [comment]
@francois-a Thank you for your information. I found another thread https://github.com/broadinstitute/gtex-pipeline/issues/11 which discusses the same issue but the link for specifying java v1.7 is no longer available https://github.com/broadinstitute/gtex-pipeline/blob/master/rnaseq/rnaseqc_counts.wdl#L21

Is specifying java version possible with docker instead of running the wdl separately? I'm really grateful for your advice.

**Comment by francois-a** [comment]
The old link is accessible at https://github.com/broadinstitute/gtex-pipeline/blob/87733c7142ac22ccd6b989193fdad119376e1118/rnaseq/rnaseqc_counts.wdl (see last comment in that thread)

**Comment by nelsonchanhk** [comment]
@francois-a Much appreciated. Just to confirm before proceeding ahead, does it mean that I have to run the new run_rnaseqc.py with wdl if I want to align with V8 and cannot use docker for this step? Have a nice weekend!
