### ISSUE TITLE
Output files from rnaseq v8 pipeline

### ISSUE THREAD

**Issue by nelsonchanhk** [broadinstitute/gtex-pipeline#53]
Hello. I finished running the v8 pipeline with docker on my own RNAseq data and there are 3 gcts generated, including sample.exon_reads.gct, sample.gene_reads.gct and sample.gene_rpkm.gct. I want to compare them with the reference dataset which uses TPM and have questions as follows.

1. From the reference v8 dataset(https://www.gtexportal.org/home/datasets), does sample.gene_reads.gct correspond to GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_reads.gct or GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_tpm.gct?

2. Is there a corresponding reference file for sample.exon_reads.gct?

3. Can I use the aggregating outputs command (docker run --rm -v $path_to_data:/data -t broadinstitute/gtex_rnaseq:V8 \
    /bin/bash -c "python3 /src/combine_GCTs.py \
        ${rnaseqc_rpkm_gcts} ${sample_set_id}.rnaseqc_rpkm"). for gcts (other than rpkm_gcts) and rsem files?

Thank you very much for your help!

**Comment by francois-a** [comment]
Hi,
1. sample.gene_reads.gct corresponds to GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_reads.gct
2. Yes, you can download this from the [GTEx Portal](https://gtexportal.org/home/datasets), the file is GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_exon_reads.parquet (in parquet format to facilitate reading the large file)
3. Yes, this function should work for any file in GCT format.

**Comment by nelsonchanhk** [comment]
@francois-a Thank you very much for your swift reply, much appreciated.

Is it possible to generate gene expression TPM directly from the v8 docker to allow comparison of own data with GTEX reference data? Have a nice day!

**Comment by francois-a** [comment]
The V8 docker produces RPKM (https://github.com/broadinstitute/gtex-pipeline/blob/0ef05fed00fd37d9ec79894cf596436a0796fe36/rnaseq/rnaseqc_counts.wdl), but you can easily convert these to TPM (as nicely described [here](https://haroldpimentel.wordpress.com/2014/05/08/what-the-fpkm-a-review-rna-seq-expression-units/) and elsewhere) -- this is what we did for the V8 analyses.

**Comment by nelsonchanhk** [comment]
Understood, thank you very much @francois-a
