### ISSUE TITLE
Question about the eQTL pipeline

### ISSUE THREAD

**Issue by nelsonchanhk** [broadinstitute/gtex-pipeline#54]
Hello. I would like to run the eQTL docker on my transcriptome sample. For the VCF input, can I use the VCF generated from from my RNA-seq experiment or should I use the vcf from WES/WGS? Thank you very much!

**Comment by francois-a** [comment]
Hi, sorry for the late response. For QTL mapping you'll ideally want to use genotypes from WGS or arrays.
