### ISSUE TITLE
Could not open genomeFastaFile:/data/Homo_sapiens_assembly38_noALT_noHLA_noDecoy_ERCC.fasta

### ISSUE THREAD

**Issue by xiyasong** [broadinstitute/gtex-pipeline#55]
Hi: I am very new to Docker and GTEx, and I am trying to use GTEx pipeline to my own RNA-seq data. However, I have stocked on the first step: build the STAR index, because it returns the following error:

Feb 10 21:14:11 ..... started STAR run
Feb 10 21:14:11 ... starting to generate Genome files

EXITING because of INPUT ERROR: could not open genomeFastaFile: /data/Homo_sapiens_assembly38_noALT_noHLA_noDecoy_ERCC.fasta

My genemoe fasta file works good on my server's STAR, so it should be a good fasta file. So I guess I have problem in my code using:
docker run --rm -v /Users/mstermo/Degree_project:/data -t broadinstitute/gtex_rnaseq:V8     /bin/bash -c "STAR \
        --runMode genomeGenerate \
        --genomeDir /data/star_index_oh100 \
        --genomeFastaFiles /data/Homo_sapiens_assembly38_noALT_noHLA_noDecoy_ERCC.fasta \
        --sjdbGTFfile /data/gencode.v26.annotation.gtf \
        --sjdbOverhang 100 \
        --runThreadN 4" 

I got confused on how to exactly substitute my own path and parameter in the command line in this pipeline? And I am not sure about my understanding of the substitution of $path_to_references:/data is correct or not. So I guess maybe that cause the problem. I make a folder called 'data' and put all the things inside.

My path is like this:
data$pwd
/Users/mstermo/Degree_project/data

data$ll
total 17537740
-rw-r--r--@ 1 mstermo  staff   8.0K Feb 10 21:58 .DS_Store
-rw-r--r--  1 mstermo  staff    25M Feb  3 11:11 .Homo_sapiens_assembly38_noALT_noHLA_noDecoy_ERCC.fasta.swp
-rwxr-xr-x  1 mstermo  staff    13G Jan 25  2019 EGAR00001121490_ccRCC-1-tumor_RNAseq.bam
-rw-r--r--@ 1 mstermo  staff    45K Jun  8  2017 Homo_sapiens_assembly38_noALT_noHLA_noDecoy_ERCC.dict
-rw-r--r--@ 1 mstermo  staff   2.9G Jun  8  2017 Homo_sapiens_assembly38_noALT_noHLA_noDecoy_ERCC.fasta
-rw-r--r--@ 1 mstermo  staff    11K Jun  8  2017 Homo_sapiens_assembly38_noALT_noHLA_noDecoy_ERCC.fasta.fai
-rwxr-xr-x@ 1 mstermo  staff    59K Feb  2 14:00 _README.TXT
-rwxr-xr-x  1 mstermo  staff   1.1G Feb  2 13:44 gencode.v26.annotation.gtf
drwxr-xr-x  3 mstermo  staff    96B Feb 10 21:54 star_index_oh100/
-rw-r--r--  1 mstermo  staff   394B Feb 10 22:15 test.sh

Thanks for your read and hoping for your help!

**Comment by francois-a** [comment]
Hi,

It looks like in the command
```
docker run --rm -v /Users/mstermo/Degree_project:/data -t broadinstitute/gtex_rnaseq:V8 /bin/bash -c ...
```
the path needs to be `-v /Users/mstermo/Degree_project/data:/data`

**Comment by xiyasong** [comment]
Thank you very much ! It worked.
