### ISSUE TITLE
Which RNA-SeQC version should be used now and what's RSEM results used for?

### ISSUE THREAD

**Issue by xiyasong** [broadinstitute/gtex-pipeline#56]
Hi!  I have read issue #53. I also generated sample.exon_reads.gct, sample.gene_reads.gct and sample.gene_rpkm.gct after running RNA-SeQC 1.1.9 in Docker V8, and have the following questions:
1: What should I do if I want to reproduce the GTEx V8 release pipeline?  Should I use RNA-SeQC 1.1.9 in V8 docker and transform sample.gene_rpkm.gct to gene_tpm.gct, then use this tpm for the eQTL analysis(using the FastQTL)? Or should I use the latest version of RNA-SeQC that is able to generate tpm file directly?
2: Why the Dockerfile in gtex-pipeline/rnaseq RNA-SeQC has been upgraded to v2.3.6, but not in actual V8 docker? 
3: I didn't understand what is the use of RSEM output? I have generated rsem.genes.results ,rsem.isoforms.results and rsem.stat, but I didn't saw where I should use them. Also, RSEM was not mentioned in GTEX 2020 paper's supplement material. 
Could you help me with those? Thank you!

**Comment by francois-a** [comment]
Hi, 
1) Unless you want to exactly reproduce results with GTEx data, I recommend using the latest version of RNA-SeQC 2. The counts will be identical or close in most cases, and the new version adds several useful metrics (and outputs TPM directly).
2) The V8 docker will not be updated, such that it can be used to reproduce V8 analyses if needed. The latest version of the pipeline uses the [V10 Dockerfile](https://github.com/broadinstitute/gtex-pipeline/blob/v10/rnaseq/Dockerfile); note that this may get updated on occasion.
3) RSEM is used to estimate isoform-level expression (as expected counts, TPMs, and ratios). It's correct that these data weren't used in the 2020 paper (we used LeafCutter intron excision ratios to quantify alternative splicing).

**Comment by xiyasong** [comment]
Many thanks for your fast reply! I understood.
