### ISSUE TITLE
Docker run eqtl_prepare_expression.py with no error but didn't generate expression.bed.gz file

### ISSUE THREAD

**Issue by xiyasong** [broadinstitute/gtex-pipeline#58]
Hi!  I met a strange issue when I use the eQTL pipeline with Docker, and I tried but failed to solve it by myself...I pulled the docker using docker pull broadinstitute/gtex_eqtl:V8, and then run the eqtl_prepare_expression.py using following code:

docker run --rm -v /Users/mstermo/Degree_Project/data:/data -t broadinstitute/gtex_eqtl:V8 /bin/bash \
    -c "/src/eqtl_prepare_expression.py /data/Total_tpm.gct /data/Total_gene_counts.gct \
        /data/GENCODE_gencode.v26.GRCh38.ERCC.genes.gtf /data/sample_participant_lookup.txt /data/EGAR00001120416_ccRCC-1-tumor.realigned.marked.BQSR.bam.g.vcf.gz_chr_list eQTL-ccRCC \
        --tpm_threshold 0.1 --count_threshold 6 --sample_frac_threshold 0.2 --normalization_method tmm"

Then the command printed these:
Loading expression data
Normalizing data (tmm)
  * 56292 genes in input tables.
  * 25692 genes remain after thresholding.
  * 25692 genes remain after removing contigs absent from VCF.
Writing BED file

And then the process broke without any information. When I check my running directory there was no bed file. 
![image](https://user-images.githubusercontent.com/67383094/110661843-3dc82780-81c5-11eb-9ac0-af8a1f8467ef.png)

I also checked my docker, it didn't break down during this process. 
Any suggestions will be very good to me ! Thank you.

**Comment by francois-a** [comment]
Hi, when using docker with this script, you'll need to specify the output directory, in your case `--output_dir /data`.

**Comment by xiyasong** [comment]
I see!! It worked, thank you.
