### ISSUE TITLE
run_FastQTL_threaded.py in Docker return error 

### ISSUE THREAD

**Issue by xiyasong** [broadinstitute/gtex-pipeline#59]
Hi! I am running run_FastQTL_threaded.py in Docker provided in this pipeline but met this error. I searched similar error in https://github.com/francois-a/fastqtl/issues/9 but the answer by stivenming didn't fix my problem: I tried to make covariates.txt into covariates.txt.gz but nothing changed. Now, this step is not working for both my own data and the example data download from https://github.com/francois-a/fastqtl/tree/master/example (with same error). I don't know how could I fix it. Appreciated any suggestion!

The code I use:
`docker run --rm -v /Users/mstermo/Degree_Project/data:/data -t broadinstitute/gtex_eqtl:V8 /bin/bash     -c "/opt/fastqtl/python/run_FastQTL_threaded.py genotypes.vcf.gz phenotypes.bed.gz example \
    --covariates covariates.txt.gz \
    --window 1e6 --chunks 100 --threads 16"`

(gunzip covariates.txt or not didn't change the error)

The error I got:
[Mar 14 23:58:02] Running FastQTL on 16 threads.
Processing chunk 1
Processing chunk 2
Processing chunk 5
Processing chunk 3
Processing chunk 4
Processing chunk 7
Processing chunk 6
Processing chunk 8
Processing chunk 9
Processing chunk 10
Processing chunk 11
Processing chunk 12
Processing chunk 13
Processing chunk 15
Processing chunk 16
Processing chunk 14
Processing chunk 17
Processing chunk 19
Processing chunk 21
Processing chunk 22
Processing chunk 25
Processing chunk 20
Processing chunk 18
Processing chunk 26
Processing chunk 27
Processing chunk 23
Processing chunk 24
Processing chunk 28
Processing chunk 29
Processing chunk 30
Processing chunk 31
Processing chunk 32
Processing chunk 33
Processing chunk 34
Processing chunk 35
Processing chunk 36
Processing chunk 37
Processing chunk 39
Processing chunk 38
Processing chunk 40
Processing chunk 41
Processing chunk 42
Processing chunk 43
Processing chunk 44
Processing chunk 45
Processing chunk 46
Processing chunk 48
Processing chunk 49
Processing chunk 50
Processing chunk 47
Processing chunk 51
Processing chunk 52
Processing chunk 54
Processing chunk 55
Processing chunk 56
Processing chunk 53
Processing chunk 57
Processing chunk 58
Processing chunk 59
Processing chunk 60
Processing chunk 62
Processing chunk 63
Processing chunk 64
Processing chunk 61
Processing chunk 65
Processing chunk 66
Processing chunk 67
Processing chunk 68
Processing chunk 69
Processing chunk 70
Processing chunk 71
Processing chunk 72
Processing chunk 73
Processing chunk 74
Processing chunk 75
Processing chunk 76
Processing chunk 77
Processing chunk 78
Processing chunk 79
Processing chunk 80
Processing chunk 81
Processing chunk 82
Processing chunk 83
Processing chunk 84
Processing chunk 85
Processing chunk 86
Processing chunk 87
Processing chunk 88
Processing chunk 89
Processing chunk 90
Processing chunk 91
Processing chunk 92
Processing chunk 93
Processing chunk 94
Processing chunk 95
Processing chunk 96
Processing chunk 97
Processing chunk 98
Processing chunk 99
Processing chunk 100
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/opt/fastqtl/python/run_FastQTL_threaded.py", line 54, in perm_worker
    s = subprocess.check_call(cmd, shell=True, executable='/bin/bash', stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/fastqtl/bin/fastQTL --vcf genotypes.vcf.gz --bed phenotypes.bed.gz --window 1e6 --maf-threshold 0.0 --ma-sample-threshold 0 --interaction-maf-threshold 0 --cov covariates.txt --chunk 1 100 --out example_chunk001.txt.gz --log example_chunk001.log' returned non-zero exit status 1
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/fastqtl/python/run_FastQTL_threaded.py", line 95, in <module>
    assert res.get()[0]==0
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
subprocess.CalledProcessError: Command '/opt/fastqtl/bin/fastQTL --vcf genotypes.vcf.gz --bed phenotypes.bed.gz --window 1e6 --maf-threshold 0.0 --ma-sample-threshold 0 --interaction-maf-threshold 0 --cov covariates.txt --chunk 1 100 --out example_chunk001.txt.gz --log example_chunk001.log' returned non-zero exit status 1

**Comment by francois-a** [comment]
Hi, 

It looks like you're not mapping the input files correctly, and `output_dir` also needs to be specified:
```
docker run --rm \
    -v /.../fastqtl/example:/data \
    -t broadinstitute/gtex_eqtl:V8 \
    /bin/bash -c "/opt/fastqtl/python/run_FastQTL_threaded.py /data/genotypes.vcf.gz /data/phenotypes.bed.gz example --covariates /data/covariates.txt.gz --window 1e6 --chunks 100 --threads 8 --output_dir /data"
```
Please check out [tensorQTL](https://github.com/broadinstitute/tensorqtl). The results and output formats will be identical to FastQTL, and the execution much simpler and faster.

**Comment by xiyasong** [comment]
Hi Francois,  thank you for this speed-reply! That now the example data is running well in the Docker. However I've tried this with my own vcf file and bed file, it seems stuck on reading my vcf file. The failed log looks like this:
![image](https://user-images.githubusercontent.com/67383094/111305521-5ae27780-8657-11eb-96d4-67e8ea94323b.png). The error in the command screen is the same as before. And I have checked sample names and chr name are same in my phenotype bed and genotype vcf.

Command I use:
docker run --rm \
    -v /Users/mstermo/Degree_Project/data:/data \
    -t broadinstitute/gtex_eqtl:V8 \
	    /bin/bash -c "/opt/fastqtl/python/run_FastQTL_threaded.py /data/Final_CombineGCVFs.sample1-2.vcf.gz /data/try-1-2.expression.bed.gz try-1-2 --covariates /data/try-1-2.PEER_covariates.txt --window 1e6 --chunks 100 --threads 8 --output_dir /data"

(I only use two samples data here as a try) 
So I wonder if it's because the vcf file format of mine is not correct. However, I generated the vcf based on the GATK best practice, since this repository didn't write details for generating vcf file. My vcf file (Final_CombineGCVFs.sample1-2.vcf.gz)header looks like this: 

![image](https://user-images.githubusercontent.com/67383094/111306730-dee92f00-8658-11eb-88ca-4b0538a14922.png)

It's different with example.genotype.vcf, so I guess maybe that's the problem? And how can I make it work on this vcf file? 
Appreciate any suggestion! 

( Thank you for the suggestion of checking out tensorQTL, I am trying to install but still need some time. And I think this problem might not be solved even if I changed to tensorQTL..)

**Comment by xiyasong** [comment]
Hi ! I just solved this problem by myself.

**Comment by SaseaR** [comment]
> Hi ! I just solved this problem by myself.

Hello, I have encountered the same problem as you. I got stuck in reading the vcf file, but I don't seem to find any problem with it. I hope you can share your solution to this problem. Thank you very much!
