### ISSUE TITLE
collapse_annotation.py fails if the input file doesn't contain comment lines

### ISSUE THREAD

**Issue by erynes** [broadinstitute/gtex-pipeline#60]
When there are no comment lines in an input file, line 251 throws an exception, no output is produced, and no explanation is given. It looks like adding a line initializing "comment" to '##' will solve this.

**Comment by francois-a** [comment]
Hi, thanks for reporting this! Fixed in e6f3c21990c199afbb9da3e4ef814274abb23ed0.

**Comment by erynes** [comment]
Merci, François!
