### ISSUE TITLE
Add pyqtl to qtl/Dockerfile so eqtl_prepare_expression.py runs smoothly

### ISSUE THREAD

**Issue by dampierch** [broadinstitute/gtex-pipeline#61]
## Intro

Thank you for maintaining this code.
I encountered an error this morning when I tried to use the latest `eqtl_prepare_expression.py` script.
I think I identified where the problem comes from, and I propose a simple solution that I think will solve it.

## Observed Error

```
singularity exec ${cont_dir}${sif} bash -c "
    ${src}eqtl_prepare_expression.py ${tpm_gct} ${reads_gct} ${gtf} \
    ${sample_participant_lookup} ${vcf_chr_list} ${prefix} \
        --tpm_threshold 0.1 \
        --count_threshold 6 \
        --sample_frac_threshold 0.2 \
        --normalization_method tmm
"
Traceback (most recent call last):
  File "gtex-pipeline/qtl/src/eqtl_prepare_expression.py", line 11, in <module>
    import qtl.io
ImportError: No module named 'qtl'
```

## Likely Problem
- `eqtl_prepare_expression.py` imports **pyqtl** since [Feb 3 2021](https://github.com/broadinstitute/gtex-pipeline/commit/23ea18655384cdd0eae14647b702c05a99afdb24#diff-cb26a21dfef5b7ba5f9825262af1aa02501e7386a6f33894081196c87455ba5bR11)
- `qtl/Dockerfile` does not install **pyqtl**

## Proposed Solution
- Add "qtl" at the end of [line 82](https://github.com/broadinstitute/gtex-pipeline/blob/e6f3c21990c199afbb9da3e4ef814274abb23ed0/qtl/Dockerfile#L82) in `qtl/Dockerfile`

**Comment by francois-a** [comment]
Thanks, fixed.
