### ISSUE TITLE
rnaseq_pipeline_fastq/bam reference invalid import

### ISSUE THREAD

**Issue by jdidion** [broadinstitute/gtex-pipeline#67]
https://api.firecloud.org/ga4gh/v1/tools/broadinstitute_gtex:rsem_v1-0_BETA/versions/5/plain-WDL/descriptor is 404

**Comment by francois-a** [comment]
Hi, where is this linked from? The correct link is https://api.firecloud.org/ga4gh/v1/tools/broadinstitute_gtex:rsem_v1-0_BETA/versions/6/plain-WDL/descriptor (version 6 instead of 5; the only difference is that the outputs are gzipped).

**Comment by jdidion** [comment]
https://github.com/broadinstitute/gtex-pipeline/blob/master/rnaseq/rnaseq_pipeline_fastq.wdl

and

https://github.com/broadinstitute/gtex-pipeline/blob/master/rnaseq/rnaseq_pipeline_bam.wdl

**Comment by francois-a** [comment]
Thanks for pointing this out! The v10 branch is up-to-date: https://github.com/broadinstitute/gtex-pipeline/blob/v10/rnaseq/rnaseq_pipeline_fastq.wdl

**Comment by jdidion** [comment]
Maybe that should be the default branch? Or the README should at least point users to that branch as the most up-to-date.

**Comment by francois-a** [comment]
Yes, that's the plan. We'll do this in the next week or so.
