### ISSUE TITLE
torus fastqtl input file

### ISSUE THREAD

**Issue by cindywen96** [broadinstitute/gtex-pipeline#69]
Hi! I have a few questions regarding the `${qtl_file}` in run_torus.py

- is it the nominal mode output file from FastQTL, with all gene-SNP pairs?
- From torus code, FastQTL format of input should have the following columns `loc_id >> snp_id >> dtss >>pval >> bhat >> sdbeta`. As the original version of FastQTL does not output `sdbeta`, I'm calculating this manually. Is it the same as `slope_se` in GTEx's enhanced version of FastQTL? Or should `slope_se` be scaled by N

Thanks a lot!

**Comment by francois-a** [comment]
Hi,

The input for Torus can be generated from the FastQTL files as follows:
`zcat $qtl_file | tail -n+2 | awk '{print $1,$2,$3,$7,$8,$9}' OFS=' ' | gzip > $torus_file`

`slope_se` is the right column to use.

**Comment by cindywen96** [comment]
Thank you!
