### ISSUE TITLE
The script does not seem to work with Ensembls GRch38 release-105 GTF file

### ISSUE THREAD

**Issue by bishwaG** [broadinstitute/gtex-pipeline#75]
Hi,
I have been using this script for Ensembl GRCh38 release 99 GTF file. Recently, I changed to release 105 GTF file and it does not seem to work. Noticed that the GTF file does not contain gene_name and transcript_name attributes for bunch of genes and transcripts.

GTF link: http://ftp.ensembl.org/pub/release-105/gtf/homo_sapiens/Homo_sapiens.GRCh38.105.gtf.gz

Error:
```
Traceback (most recent call last):
  File "/fas/NGS/pipelines/FIMM-RNASeq/v2.0.7/bin/collapse_annotation.py", line 267, in <module>
    annotation = Annotation(args.transcript_gtf)
  File "/fas/NGS/pipelines/FIMM-RNASeq/v2.0.7/bin/collapse_annotation.py", line 74, in __init__
    g = Gene(gene_id, attributes['gene_name'], attributes['gene_type'], chrom, strand, start_pos, end_pos)
KeyError: 'gene_name'
```

**Comment by francois-a** [comment]
Hi,
Please use the latest version of this script available [here](https://github.com/broadinstitute/gtex-pipeline/blob/master/gene_model/collapse_annotation.py), which works with this GTF.
