### ISSUE TITLE
Population-based phasing reference panel

### ISSUE THREAD

**Issue by teng-gao** [broadinstitute/gtex-pipeline#78]
Hi,

I was wondering which population phasing reference panel (1000G? HRC?) was used to pre-phase the WGS genotypes in the GTEx v8 VCFs, since I could not find that information on the GTEx website or publications.

Thanks,
Teng

**Comment by francois-a** [comment]
Please see Section 2.4 in the [supplement](https://www.science.org/doi/suppl/10.1126/science.aaz1776/suppl_file/aaz1776_aguet_sm.pdf) of the 2020 GTEx paper for details on the phasing.
