### ISSUE TITLE
access to gtex-resources on google cloud

### ISSUE THREAD

**Issue by limrock1** [broadinstitute/gtex-pipeline#79]
Hi,

Sorry if this is an old topic but I haven't seen any threads about it. I'm trying to get access to some of the gtex reference data on the google resources site (e.g. https://storage.googleapis.com/gtex-resources/GENCODE/gencode.v39.GRCh38.genes.gtf) but am getting the dreaded bucket pays error below. Any solution to this aside from getting a google cloud account? 

"Bucket is a requester pays bucket but no user project provided"

Thanks, Sean.

**Comment by francois-a** [comment]
Please see https://gtexportal.org/home/faq#requesterPays.
