### ISSUE TITLE
command to run rnaseqc in the docker image

### ISSUE THREAD

**Issue by jfertaj** [broadinstitute/gtex-pipeline#8]
Hi, in the readme file there is no command to run the quantification of rnaseqc

# RSEM transcript quantification
docker run --rm -v $path_to_data:/data -t broadinstitute/gtex_rnaseq /bin/bash -c "/src/run_RSEM.py /data/rsem_reference /data/star_out/$prefix.Aligned.toTranscriptome.out.bam /data/$prefix --threads 1"

Could you provide me with an example to run the last step to get the tpms and proceed then to qtl pipeline? thanks

**Comment by francois-a** [comment]
Please see the updated [README](https://github.com/broadinstitute/gtex-pipeline/blob/master/rnaseq/README.md).
