### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by qicaibiology** [broadinstitute/gtex-pipeline#85]
I was trying to run the command using: 
`python3 collapse_annotation.py gencode.vM25.annotation.gtf gencode.vM25.genes.gtf `

I used anacondas environment to use python3, and use gencode.vM25.annotation.gtf as input and output is supposed to be gencode.vM25.genes.gtf. I got the following error and I don't know what to do:

> File "/gpfs/gibbs/project/sestan/cq39/PMID_30678683/combined_bams/collapse_annotation.py", line 76
>     <title>gtex-pipeline/gene_model/collapse_annotation.py at master · broadinstitute/gtex-pipeline · GitHub</title>
>                                                                      ^
> SyntaxError: invalid character '·' (U+00B7)

Thanks

**Comment by francois-a** [comment]
The script runs fine on this GTF (https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M25/gencode.vM25.annotation.gtf.gz), this must be an issue with your environment.
