### ISSUE TITLE
when getting 'transcript' or 'gene' from the gtf file.

### ISSUE THREAD

**Issue by ningbioinfostruggling** [broadinstitute/gtex-pipeline#9]
Hi, I am currently using the eqtl_prepare_expresson.py to prepare my expression data.
I noticed that default setting of the function gtf_to_bed is to get the 'gene' instead of 'transcript', while the script uses 'transcript' to call the function in line 174.

And the number of the feature is largely different in the gtf file:
``` 
$ awk '$3=="transcript"' eqtl_data/gencode.v27lift37.annotation.gtf| wc -l
  202697
```
```
 $ awk '$3=="gene"' eqtl_data/gencode.v27lift37.annotation.gtf| wc -l
   60461
```

So I am wondering which is the proper one to use?

**Comment by francois-a** [comment]
You first need to generate a collapsed, gene-level GTF for this pipeline. I've added this to the README: https://github.com/broadinstitute/gtex-pipeline/tree/master/qtl#running-the-pipeline
